### ISSUE TITLE
Why are there black boxes under entities?

### ISSUE THREAD

**Issue by GPUawa** [NoComment1105/YoFPS-Chocapic13-edit#1]
1.19.3+fabric+sodium+iris
Please tell me why.
Thanks!
[](https://cdn.luogu.com.cn/upload/image_hosting/oafr5pci.png)

**Comment by GPUawa** [comment]
![Uploading 2023-08-09_08.32.21.png…]()

**Comment by GPUawa** [comment]
OK.I just solve it.

**Comment by yogeshdofficial** [comment]
> OK.I just solve it.

pls say how?
